/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TeaCryptoManager */

#ifndef _Included_TeaCryptoManager
#define _Included_TeaCryptoManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TeaCryptoManager
 * Method:    NativeEncrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_TeaCryptoManager_NativeEncrypt
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     TeaCryptoManager
 * Method:    NativeDecrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_TeaCryptoManager_NativeDecrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
